//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyTailV3.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Budgets
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Budgets()
        {
            this.TotalSpent = 0.0m;
            this.Transactions = new HashSet<Transactions>();
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public short UserId { get; set; }
        public decimal TotalSpent { get; set; }
        public decimal TotalAllocated { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transactions> Transactions { get; set; }
        public virtual Users User { get; set; }
    }
}
