//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MoneyTailV3.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Transactions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Transactions()
        {
            this.Amount = 0.0m;
        }
    
        public int Id { get; set; }
        public string Name { get; set; }
        public short UserId { get; set; }
        public decimal Amount { get; set; }
        public Nullable<short> BudgetId { get; set; }
        public System.DateTime Date { get; set; }
        public string Category { get; set; }
    
        public virtual Budgets Budget { get; set; }
        public virtual Users User { get; set; }
    }
}
